name: Compile Latex 


on:
  pull_request:
    branches: [ main, master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          # Установка biber и сборка LaTeX
          apt-get update && apt-get install -y biber
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main.tex
          biber main
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main.tex
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error main.tex